spring:
  application:
    name: upstox-algo-ws
  config:
    import: file:${FILE_LOCATION}
  profiles:
    active: ${SPRING_ACTIVE_PROFILES}
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML
  data:
    mongodb:
      host: localhost
      port: 27017
      database: algo
server:
  port: 8082
logging:
  level:
    com.algo: ${LOGGING_LEVEL_COM_ALGO:INFO}
    org.mongodb: OFF
    com.mongodb: OFF
    org.springframework: INFO

trade:
  rr-ratio: 1

app:
  login:
    config:
      redirect-url: ${REDIR_URL:unknown}
      broker-host: ${BROKER_HOST:unknown}
      market-start-time: "09:15:00"
      market-end-time: "15:30:00"
      login-refresh-time: "06:00:00"
  config:
    trade:
      lot-multiplier: ${LOT_MULTIPLIER:1}
      candle-data-durations:
        - 1m
        - 3m
        - 5m
        - 15m
        - 75m
      moving-averages:
        - 5
        - 10
        - 20
        - 50
        - 100
        - 200
      ema-smoothing: 2
      buy-timeframe: 15m
      sell-timeframe: 5m
      stoploss-points: 15
      risk-reward-ratio: 2
      quantity: 450
      half-quantity: 225
      test-quantity: 150
    scrips:
      - name: NIFTY
        trading-symbol: NSE_INDEX|Nifty 50
        lot-size: 25
        strike-diff: 50
        expiry-day: THURSDAY
        no-trade-after: "14:55:00"
        premium-selection:
          FRIDAY:
            - from: "09:15:00"
              to: "15:30:00"
              min-premium: 100
              max-premium: 120
          MONDAY:
            - from: "09:15:00"
              to: "15:30:00"
              min-premium: 80
              max-premium: 95
          TUESDAY:
            - from: "09:15:00"
              to: "15:30:00"
              min-premium: 61
              max-premium: 72
          WEDNESDAY:
            - from: "09:15:00"
              to: "12:29:59"
              min-premium: 45
              max-premium: 59
            - from: "12:30:00"
              to: "15:30:00"
              min-premium: 35
              max-premium: 45
          THURSDAY:
            - from: "09:15:00"
              to: "11:59:59"
              min-premium: 30
              max-premium: 41
            - from: "12:00:00"
              to: "15:30:00"
              min-premium: 12
              max-premium: 22
        exchanges:
          - NSE
          - NFO

    platform:
      asset-url: ${ASSET_URL:unknown}
      holiday-list-url: ${HOLIDAY_LIST_URL:unknown}
      asset-download-path: ${ASSET_FILE_LOCATION:unknown}
      asset-name-date-format: 'yyyyMMMdd'
      asset-download-name-prefix: 'NSE_Contracts_'
      asset-download-name-suffix: '.json'
      trading-symbol-pattern: '<instrumentName> <strike> <instrumentType> <expiryDate>'
      trading-symbol-date-format: 'dd MMM yy'