package com.algo.upstox.api.model;

public enum MessageCategoryEnum {
    LTPC, TRADE_PLAN, POSITION_UPDATE, INVALID_SESSION, STRADDLE, SUBSCRIBE, EVENT, ALERT_TRIGGERED,
    HOLDING_FETCHED, HOLDING_SUM_STREAM, POSITION_FETCHED
}
